version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - unparam
  settings:
    misspell:
      locale: US
  exclusions:
    paths:
      - examples

formatters:
  enable:
    - goimports
