version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-checks:
        - appendAssign
        - dupBranchBody
        - dupCase
        - equalFold
        - sloppyLen
    misspell:
      locale: US
  exclusions:
    paths:
      - examples

formatters:
  enable:
    - goimports
